### ISSUE TITLE
Frage:

### ISSUE THREAD

**Issue by jbovermann** [durek1337/gymhaan#1]
ja

**Comment by durek1337** [comment]
Manchmal benötigt man einen Schlüssel, um darauf zuzugreifen. Der wird dann mit curl geholt und über eine Pipe ```|``` an den Folgebefehl übergeben.
Bei "scripts/postgresql.sh" kommt das einmal vor. Da wäre es sogar nicht nötig, insofern man sich mit postgresql v10 zufrieden geben möchte, wenn man es mit ```sudo apt install postgresql``` installiert. Solltest du die Scripts effizienter gestalten können, tu dir keinen Zwang an und forke das repository und mache einen Pull Request ;-) Mit dem Git hatte ich vorallem die Hoffnung, dass auch Schüler/innen sich daran beteiligen können und wir gemeinsam ein System basteln, mit dem wir alle zufrieden sind!
